name: Publish NuGet package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish NuGet package
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      run: |
        cd Sources/TelegramBot
        dotnet build --configuration Release
        dotnet pack --configuration Release --output nupkg
        dotnet nuget add source --username BigMakCode --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/BigMakCode/index.json"
        dotnet nuget push nupkg/*.nupkg --skip-duplicate --api-key $GITHUB_TOKEN --source "github"
        dotnet nuget push nupkg/*.nupkg --skip-duplicate --api-key $NUGET_KEY --source https://api.nuget.org/v3/index.json
